In [3]:
import numpy as np

ONLY FIRST 16 FRAMES

In [9]:
# Load the .npy file
data = np.load('C:/Users/xoni/Documents/1_uni/1_insterships/UR-DMU/feature_extract/UCF_ten/Shoplifting049_x264_16_frames.npy')  # Replace with the actual file path

# Print the contents of the .npy file
print(data)
print(data.shape)

[[[0.24833742 0.09300754 0.24000742 ... 0.09318355 0.07297391 0.00506544]]

 [[0.22613648 0.15912296 0.15854874 ... 0.2774687  0.0070546  0.00883143]]

 [[0.14336061 0.1629134  0.05784485 ... 0.09272229 0.27622208 0.06273043]]

 ...

 [[0.31873968 0.20608826 0.09738021 ... 0.20660476 0.0223036  0.02984428]]

 [[0.443656   0.15127696 0.18755609 ... 0.14214855 0.00126638 0.04270414]]

 [[0.33358914 0.13362437 0.25507924 ... 0.15139373 0.1000688  0.07922807]]]
(10, 1, 1024)


32 FRAMES

In [10]:
# Load the .npy file
data = np.load('C:/Users/xoni/Documents/1_uni/1_insterships/UR-DMU/feature_extract/UCF_ten/Shoplifting049_x264_32_frames.npy')  # Replace with the actual file path

# Print the contents of the .npy file
print(data)
print(data.shape)

[[[0.24852538 0.09300525 0.23996055 ... 0.0932684  0.07281173 0.00511163]
  [0.26407272 0.1037299  0.20576224 ... 0.07400725 0.07643509 0.00249433]]

 [[0.22617434 0.15911539 0.15861765 ... 0.2778535  0.00716087 0.00882578]
  [0.18483739 0.13185953 0.1919492  ... 0.16356146 0.06240939 0.02868354]]

 [[0.14342839 0.16282353 0.05782957 ... 0.09266748 0.27625299 0.0627339 ]
  [0.1553983  0.13087349 0.08223739 ... 0.01588702 0.12496347 0.05833935]]

 ...

 [[0.31890768 0.20589224 0.09733034 ... 0.20663184 0.02220407 0.02978505]
  [0.29838973 0.17764021 0.12241258 ... 0.14466497 0.03026484 0.07834432]]

 [[0.44363514 0.15129334 0.18757723 ... 0.14212929 0.00128123 0.04298785]
  [0.3504879  0.17191894 0.23822637 ... 0.04232416 0.         0.02837723]]

 [[0.33374643 0.13367093 0.25507817 ... 0.15143648 0.10011989 0.07936261]
  [0.3608639  0.1391296  0.27126434 ... 0.15911652 0.16829851 0.02610402]]]
(10, 2, 1024)


TODOS LOS FRAMES

In [8]:
# Load the .npy file
data = np.load('C:/Users/xoni/Documents/1_uni/1_insterships/UR-DMU/feature_extract/UCF_ten/Shoplifting049_x264_i3d_GPU.npy')  # Replace with the actual file path

# Print the contents of the .npy file
print(data)
print(data.shape)

[[[0.24762356 0.09154781 0.26749486 ... 0.08056443 0.08192731 0.01008778]
  [0.26074666 0.10192531 0.20897815 ... 0.09159835 0.08250418 0.00170188]
  [0.24906695 0.09424378 0.22615857 ... 0.0622921  0.09180505 0.0050545 ]
  ...
  [0.42257792 0.1176526  0.3875741  ... 0.08120591 0.21674415 0.0142264 ]
  [0.2610433  0.         0.32217044 ... 0.22948863 0.4346882  0.03935197]
  [0.16544779 0.04619792 0.27711013 ... 0.24410139 0.0877016  0.09973854]]

 [[0.23858407 0.1634851  0.15860018 ... 0.25729012 0.00930962 0.00617585]
  [0.19454753 0.13246688 0.19704151 ... 0.1854426  0.04789664 0.03969092]
  [0.14806853 0.12061595 0.1780253  ... 0.1515173  0.1075684  0.04310748]
  ...
  [0.13341707 0.11593488 0.16241695 ... 0.27303156 0.16615638 0.11994308]
  [0.22049555 0.10720638 0.17170498 ... 0.38870025 0.18168584 0.08882296]
  [0.1854299  0.06497803 0.15746814 ... 0.63724786 0.15186904 0.1426497 ]]

 [[0.13828988 0.158587   0.05843603 ... 0.06962644 0.27779442 0.07031728]
  [0.16432045 0.123482

un archivo extraido entero

In [4]:
# Load the .npy file
import os
import numpy as np
data = np.load('C:/Users/xoni/Documents/1_uni/1_insterships/UR-DMU/feature_extract/UCF_ten/Abuse028_x264_i3d.npy')  # Replace with the actual file path

# Print the contents of the .npy file
print(data)
print(data.shape)

[[[0.26942024 0.1617896  0.10704    ... 0.3238298  0.09678405 0.36583567]
  [0.19056694 0.14125705 0.11378231 ... 0.231105   0.06342842 0.4446679 ]
  [0.23900488 0.18802994 0.12608467 ... 0.32964697 0.01131064 0.39195547]
  ...
  [0.20775764 0.13021219 0.10157082 ... 0.473874   0.17021932 0.563565  ]
  [0.20448238 0.12456121 0.09880609 ... 0.56455463 0.21634176 0.58929056]
  [0.21014206 0.13138811 0.10433579 ... 0.48917645 0.13987175 0.54219514]]

 [[0.28557348 0.15544502 0.13721846 ... 0.29797512 0.1205657  0.24883358]
  [0.28998205 0.18526374 0.16747266 ... 0.19922702 0.1161687  0.2957285 ]
  [0.41048697 0.17475066 0.17934556 ... 0.09094975 0.14855364 0.21771652]
  ...
  [0.33238313 0.15041156 0.13766612 ... 0.6394371  0.21105361 0.22991376]
  [0.30500892 0.1474018  0.14059886 ... 0.63245875 0.22343044 0.24703096]
  [0.29600564 0.15236565 0.15229529 ... 0.5770925  0.2362636  0.21833739]]

 [[0.26667973 0.11606093 0.1012269  ... 0.15151681 0.09761553 0.45519647]
  [0.26005647 0.171825

In [3]:
import cv2

# Cargar la imagen
imagen = cv2.imread('C:/Users/xoni/Documents/1_uni/1_insterships/UR-DMU/feature_extract/UCF_Crime_Frames/Abuse028_x264/img_00000001.jpg')

# Obtener las dimensiones
alto, ancho, canales = imagen.shape

# Mostrar el tamaño
print(f"El tamaño de la imagen es: {ancho}x{alto} píxeles")


El tamaño de la imagen es: 320x240 píxeles


crear nuevo test_train.list que no contenga los archivos con diferente tamaño

In [9]:
# Importar las librerías necesarias
import os

# Función para leer un archivo .list y obtener los nombres de los archivos
def leer_archivo_list(ruta_archivo):
    with open(ruta_archivo, 'r') as f:
        lineas = f.readlines()
    # Eliminar cualquier salto de línea y devolver una lista de los archivos
    return [linea.strip() for linea in lineas]

# Función para eliminar los archivos que están en la lista de exclusión (incluyendo variantes)
def filtrar_archivos(original_files, exclusion_files):
    archivos_filtrados = []
    for archivo in original_files:
        # Si ningún archivo de la lista de exclusión es un prefijo del archivo actual, lo mantenemos
        if not any(os.path.basename(archivo).startswith(os.path.splitext(exclusion)[0]) for exclusion in exclusion_files):
            archivos_filtrados.append(archivo)
    return archivos_filtrados

# Función para escribir los archivos filtrados en un nuevo archivo .list
def escribir_archivo_list(ruta_archivo, archivos):
    with open(ruta_archivo, 'w') as f:
        for archivo in archivos:
            f.write(archivo + '\n')

# Rutas de los archivos de entrada y salida
ruta_original_list = 'list/Test_Train_excluido.list'  # Reemplaza con la ruta correcta
ruta_exclusion_list = 'list/excluir_URDMU.list'  # Reemplaza con la ruta correcta
ruta_nuevo_list = 'list/Test_Train_excluido_URDMU.list'  # Reemplaza con la ruta correcta

# Leer los archivos desde los .list
archivos_originales = leer_archivo_list(ruta_original_list)
archivos_a_excluir = leer_archivo_list(ruta_exclusion_list)

# Filtrar los archivos (eliminar los que tienen el mismo prefijo que en la lista de exclusión)
archivos_filtrados = filtrar_archivos(archivos_originales, archivos_a_excluir)

# Escribir el nuevo archivo .list con los archivos filtrados
escribir_archivo_list(ruta_nuevo_list, archivos_filtrados)

# Mostrar resultado en la salida
print(f"Se ha creado un nuevo archivo con {len(archivos_filtrados)} archivos filtrados en '{ruta_nuevo_list}'.")



Se ha creado un nuevo archivo con 15360 archivos filtrados en 'list/Test_Train_excluido_URDMU.list'.


In [5]:
import os

# Función para obtener la lista de archivos en una carpeta
def obtener_archivos_en_carpeta(ruta_carpeta):
    # Obtener solo los nombres de los archivos (sin la ruta completa)
    return set(os.listdir(ruta_carpeta))

# Rutas de las carpetas
ruta_carpeta_1 = 'C:/Users/xoni/Documents/1_uni/1_insterships/cuda_version/PEL4VAD-master/predictions/train'  # Reemplaza con la ruta de la primera carpeta
ruta_carpeta_2 = 'C:/Users/xoni/Documents/1_uni/1_insterships/UR-DMU/frame_label/predictions/train'  # Reemplaza con la ruta de la segunda carpeta

# Obtener los archivos en ambas carpetas
archivos_carpeta_2 = obtener_archivos_en_carpeta(ruta_carpeta_1)
archivos_carpeta_1 = obtener_archivos_en_carpeta(ruta_carpeta_2)

# Determinar qué archivos están en la primera carpeta pero no en la segunda
archivos_faltantes = archivos_carpeta_1 - archivos_carpeta_2

# Mostrar los archivos faltantes en la celda del notebook
if archivos_faltantes:
    print(f"Archivos en la primera carpeta que no están en la segunda ({len(archivos_faltantes)} archivos):")
    for archivo in archivos_faltantes:
        print(archivo)
else:
    print("Todos los archivos de la primera carpeta están presentes en la segunda carpeta.")



Archivos en la primera carpeta que no están en la segunda (71 archivos):
Normal_Videos410_pred.npy
Normal_Videos764_pred.npy
Stealing066_pred.npy
RoadAccidents078_pred.npy
Robbery089_pred.npy
Robbery109_pred.npy
Normal_Videos183_pred.npy
Normal_Videos060_pred.npy
Robbery117_pred.npy
Normal_Videos395_pred.npy
Burglary085_pred.npy
Normal_Videos946_pred.npy
Assault036_pred.npy
Normal_Videos160_pred.npy
Stealing023_pred.npy
Stealing080_pred.npy
Normal_Videos180_pred.npy
Normal_Videos830_pred.npy
Burglary067_pred.npy
Stealing074_pred.npy
Normal_Videos277_pred.npy
Normal_Videos255_pred.npy
Normal_Videos472_pred.npy
Stealing027_pred.npy
Stealing096_pred.npy
Normal_Videos285_pred.npy
Shooting044_pred.npy
Burglary064_pred.npy
Burglary072_pred.npy
Vandalism025_pred.npy
Normal_Videos259_pred.npy
Explosion046_pred.npy
Normal_Videos659_pred.npy
RoadAccidents142_pred.npy
Normal_Videos653_pred.npy
Arrest014_pred.npy
Normal_Videos425_pred.npy
Normal_Videos112_pred.npy
Normal_Videos947_pred.npy
Robbery

In [40]:
import os

def archivos_unicos(carpeta1, carpeta2):
    # Obtener los nombres de archivos en cada carpeta
    archivos_carpeta1 = set(os.listdir(carpeta1))
    archivos_carpeta2 = set(os.listdir(carpeta2))
    archivos_carpeta1 = set([i.split('_x264')[0] for i in archivos_carpeta1])
    # print(archivos_carpeta1)
    archivos_carpeta2 = set([i.split('_x264')[0] for i in archivos_carpeta2])
    # print(archivos_carpeta2)
    unicos_carpeta1 = archivos_carpeta1 - archivos_carpeta2
    print(len(unicos_carpeta1))
    return list(unicos_carpeta1)

# Ejemplo de uso
carpeta1 = 'test'
carpeta2 = 'test/rgb_test'

archivos_faltantes = archivos_unicos(carpeta1, carpeta2)
for i in archivos_faltantes:
    print(i)


3
C_i3d.npy
rgb_test
15


In [46]:
def archivos_unicos(lista1, lista2):
    # Leer los nombres de archivos desde cada lista
    with open(lista1, 'r') as f1:
        archivos_lista1 = set([line.strip().split('_x264')[0] for line in f1])
        archivos_lista1 = set([i.split('/')[1] for i in archivos_lista1])
        print(archivos_lista1)

    with open(lista2, 'r') as f2:
        archivos_lista2 = set([line.strip().split('_x264')[0] for line in f2])
        archivos_lista2 = set([i.split('rgb_test/')[1] for i in archivos_lista2])
        print(archivos_lista2)

    # Calcular la diferencia entre las dos listas
    unicos_lista1 = archivos_lista1 - archivos_lista2
    print(f"Total de archivos únicos en {lista1} que no están en {lista2}: {len(unicos_lista1)}")
    return list(unicos_lista1)

# Ejemplo de uso
lista1 = 'list/UCF_Test.list'  # Reemplazar con la ruta del primer archivo de lista
lista2 = 'list/UCF_Test_rgb.list'  # Reemplazar con la ruta del segundo archivo de lista

archivos_faltantes = archivos_unicos(lista1, lista2)
for archivo in archivos_faltantes:
    print(archivo)


{'Shoplifting017', 'Explosion007', 'Normal_Videos_944', 'RoadAccidents133', 'RoadAccidents132', 'Normal_Videos_938', 'Normal_Videos_439', 'Normal_Videos_882', 'Fighting003', 'Normal_Videos_933', 'Arson007', 'Stealing079', 'Normal_Videos_182', 'Normal_Videos_880', 'Explosion004', 'Normal_Videos_872', 'Normal_Videos_932', 'Explosion028', 'Normal_Videos_168', 'Normal_Videos_758', 'Normal_Videos_935', 'Normal_Videos_129', 'Vandalism028', 'Normal_Videos_289', 'Normal_Videos_710', 'Shoplifting010', 'Shooting008', 'Normal_Videos_831', 'Assault010', 'Normal_Videos_911', 'Normal_Videos_873', 'Normal_Videos_634', 'Shoplifting039', 'Shoplifting031', 'Normal_Videos_877', 'Shooting033', 'Normal_Videos_196', 'Normal_Videos_783', 'Normal_Videos_024', 'Normal_Videos_189', 'Normal_Videos_312', 'Normal_Videos_042', 'Shoplifting005', 'Arson035', 'Explosion043', 'Fighting047', 'Normal_Videos_902', 'Normal_Videos_246', 'Robbery050', 'Normal_Videos_895', 'RoadAccidents011', 'Stealing036', 'Normal_Videos_725

In [1]:
# Load the .npy file
import os
import numpy as np
og = np.load('test/Abuse028_x264.npy')  # Replace with the actual file path
rgb = np.load('test/rgb_test/Abuse028_x264.npy')  # Replace with the actual file path
quince = np.load('test/15/Abuse028_x264_i3d.npy')
quince_mean = np.mean(quince, axis=0)


# Print the contents of the .npy file
print("og:")
print(og.shape)
print(og[0:20])


print("rgb:")
print(rgb.shape)
print(rgb[0:20])


print("quince:")
print(quince.shape)
print(quince[0:20])

# print("quince_mean:")
# print(quince_mean.shape)
# print(quince_mean)




og:
(88, 1024)
[[0.21641299 0.13433068 0.10196356 ... 0.1655554  0.03033594 0.21674377]
 [0.26922452 0.17096406 0.11051404 ... 0.28062525 0.03870422 0.374596  ]
 [0.3121737  0.21388486 0.12493171 ... 0.23084582 0.03025872 0.780828  ]
 ...
 [0.3417933  0.20007889 0.13387579 ... 0.1877338  0.12898876 0.33882344]
 [0.34481484 0.15510535 0.11880767 ... 0.15291433 0.18363024 0.33008665]
 [0.31634516 0.20063777 0.16611174 ... 0.32080388 0.4744656  0.5425052 ]]
rgb:
(88, 1024)
[[0.1496628  0.1205172  0.20712942 ... 0.3527503  0.19229601 0.25662577]
 [0.14061813 0.13039592 0.19647859 ... 0.35073966 0.14490552 0.22396845]
 [0.19171259 0.15795608 0.21602966 ... 0.19380198 0.20517185 0.33191696]
 ...
 [0.18930727 0.09166858 0.2326933  ... 0.30498934 0.19793166 0.45760742]
 [0.16260408 0.1145008  0.23491643 ... 0.22453485 0.15900007 0.47372115]
 [0.20470916 0.11025376 0.2334838  ... 0.1634879  0.11394446 0.40453544]]
quince:
(10, 6, 1024)
[[[0.00000000e+00 1.18591572e-07 1.17503383e-07 ... 0.00000

Comprobar si rgb es la media de los 10 vectores de la original

In [40]:
# Load the .npy file
import os
import numpy as np

og = []
for i in range(10):
    if i>0:
        data = np.load(f'test/Abuse028_x264__{i}.npy')  # Replace with the actual file path
    else:
        data = np.load(f'test/Abuse028_x264.npy')

    #añadir a siguiente vector
    og.append(data)
    # print(len(og))
   
og = np.stack(og, axis=0)
og = np.mean(og, axis=0)

rgb = np.load('test/rgb_test/Abuse028_x264.npy')  # Replace with the actual file path


# Print the contents of the .npy file
print("la media del og:")
print(og.shape)
print(og[0])


print("rgb:")
print(rgb.shape)
print(rgb[0][0])

print("mio:")
mio = np.load('feature_extract/UCF_ten/repeat/Burglary005_x264_i3d.npy')  # Replace with the actual file path
print(mio.shape)
print(mio[0][0])



la media del og:
(88, 1024)
[0.25383362 0.14242038 0.15957433 ... 0.32468262 0.09209806 0.3923364 ]
rgb:
(88, 1024)
0.1496628
mio:
(10, 484, 1024)
[2.6834418e-06 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00 0.0000000e+00
 3.4926381e-06]


comparar original con el extraido con mi i3d

In [37]:
import os
import numpy as np

og = []
for i in range(10):
    if i>0:
        data = np.load(f'test/Burglary005_x264__{i}.npy')  # Replace with the actual file path
    else:
        data = np.load(f'test/Burglary005_x264.npy')

    #añadir a siguiente vector
    og.append(data)
    # print(len(og))
   
og = np.stack(og, axis=0)

print("og:")
print(og.shape)
print(og[0][0])

print("mio:")
mio = np.load('feature_extract/UCF_ten/repeat/Burglary005_x264_i3d.npy')  # Replace with the actual file path
print(mio.shape)
print(mio[0][0])

print("mio:")
mio = np.load('feature_extract/UCF_ten/10porciento/Burglary005_x264_010_i3d.npy')  # Replace with the actual file path
print(mio.shape)
print(mio[0][0])

og:
(10, 483, 1024)
[0.276627   0.41552758 0.16309164 ... 0.1495911  0.21706213 0.19547334]
mio:
(10, 484, 1024)
[2.6834418e-06 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00 0.0000000e+00
 3.4926381e-06]
mio:
(10, 490, 1024)
[0.04445615 0.15347521 0.0605179  ... 0.         0.03228812 0.07629051]


In [1]:
# Load the .npy file
import os
import numpy as np
og = np.load('frame_label/predictions/test/Abuse028_pred.npy')  # Replace with the actual file path
rgb = np.load('frame_label/predictions/test/rgb/Abuse028_pred.npy')  # Replace with the actual file path
quince = np.load('frame_label/predictions/test/quince/Abuse028_pred.npy')


# Print the contents of the .npy file
print("og:")
print(og.shape)
print(og)


print("new:")
print(rgb.shape)
print(rgb)


print("quince:")
print(quince.shape)
print(quince)


og:
(1408,)
[0.83650154 0.83650154 0.83650154 ... 0.3961795  0.3961795  0.3961795 ]
new:
(1408,)
[1.5466608e-06 1.5466608e-06 1.5466608e-06 ... 9.6295696e-07 9.6295696e-07
 9.6295696e-07]
quince:
(1440,)
[0.9506095  0.9506095  0.9506095  ... 0.95063925 0.95063925 0.95063925]


Guardar solo los .npy de test de las nuevas features descargadas

In [22]:
import os
import numpy as np

# Rutas de las carpetas
ruta_features = 'test/15'  
ruta_test = 'test'  
ruta_output = 'test/15'  

# Obtener la lista de nombres de los archivos de test a partir de la carpeta de preds
nombres_test = [f.split('_x264')[0] for f in os.listdir(ruta_test) if f.endswith('.npy')]

# Crear la carpeta de salida si no existe
os.makedirs(ruta_output, exist_ok=True)

# Mantener un conjunto de nombres únicos
nombres_guardados = set()

# Recorrer la carpeta de features
for nombre in nombres_test:
    # Definir la ruta de la carpeta de features correspondiente
    nombre = f'{nombre}_x264'
    carpeta_features = os.path.join(ruta_features, nombre)
    
    # Verificar si la carpeta existe y si contiene el archivo 'features.npy'
    archivo_features = os.path.join(carpeta_features, 'feature.npy')
    if os.path.exists(archivo_features):
        # Cargar el archivo .npy
        features = np.load(archivo_features)
        
        # Guardar las features con el nombre correspondiente en la carpeta de salida
        archivo_salida = os.path.join(ruta_output, f"{nombre}.npy")
        np.save(archivo_salida, features)
        
        # Añadir el nombre al conjunto de nombres únicos
        nombres_guardados.add(archivo_salida)
        print(f"{archivo_salida}")
    else:
        print(f"No se encontró 'features.npy' en la carpeta: {carpeta_features}")

# Guardar los nombres únicos en un archivo de texto
with open('test/rgb_test/nombres_test.txt', 'w') as f:
    for nombre in sorted(nombres_guardados):
        f.write(f"{nombre}\n")



test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse028_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Abuse030_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest001_x264.npy
test/rgb_test\Arrest007_x264.n

Comarar tamaños de los archivos .npy

In [24]:
import os
import numpy as np

# Rutas de las carpetas de los archivos originales y nuevos
ruta_og = 'test'  # Cambia esta ruta por la correspondiente a tus archivos originales
ruta_new = 'test/rgb_test'  # Cambia esta ruta por la correspondiente a tus nuevos archivos

# Obtener la lista de archivos de ambas carpetas
archivos_og = [f for f in os.listdir(ruta_og) if f.endswith('.npy')]
archivos_new = [f for f in os.listdir(ruta_new) if f.endswith('.npy')]

# Lista para almacenar los archivos con tamaños diferentes
archivos_diferentes = []

# Comparar tamaños de cada archivo
for archivo in archivos_og:
    # Verificar si el archivo correspondiente existe en la carpeta nueva
    if archivo in archivos_new:
        ruta_og_archivo = os.path.join(ruta_og, archivo)
        ruta_new_archivo = os.path.join(ruta_new, archivo)
        
        # Cargar ambos archivos .npy
        og = np.load(ruta_og_archivo)
        new = np.load(ruta_new_archivo)
        
        # Comparar las formas (shapes) de los archivos
        if og.shape != new.shape:
            archivos_diferentes.append((archivo, og.shape, new.shape))

# Mostrar los archivos que tienen tamaños diferentes
if archivos_diferentes:
    print("Archivos con tamaños diferentes:")
    for archivo, shape_og, shape_new in archivos_diferentes:
        print(f"{archivo}: original {shape_og}, nuevo {shape_new}")
else:
    print("Todos los archivos tienen el mismo tamaño.")


Archivos con tamaños diferentes:
Arson022_x264.npy: original (540, 1024), nuevo (539, 1024)
Assault011_x264.npy: original (143, 1024), nuevo (142, 1024)
Normal_Videos_015_x264.npy: original (30, 1024), nuevo (29, 1024)
Normal_Videos_033_x264.npy: original (105, 1024), nuevo (104, 1024)
Normal_Videos_150_x264.npy: original (54, 1024), nuevo (53, 1024)
Normal_Videos_210_x264.npy: original (338, 1024), nuevo (337, 1024)
Normal_Videos_641_x264.npy: original (225, 1024), nuevo (224, 1024)
Normal_Videos_831_x264.npy: original (28, 1024), nuevo (27, 1024)
Normal_Videos_867_x264.npy: original (39, 1024), nuevo (38, 1024)
Normal_Videos_923_x264.npy: original (1139, 1024), nuevo (1138, 1024)
Normal_Videos_924_x264.npy: original (6749, 1024), nuevo (6250, 1024)
Normal_Videos_935_x264.npy: original (6749, 1024), nuevo (6250, 1024)
Shoplifting029_x264.npy: original (136, 1024), nuevo (135, 1024)


In [ ]:
import os

# Ruta al archivo .list
list_file = 'list/UCF_Train.list'

# Ruta a la carpeta principal de 'train'
train_folder = 'UCF_Crime_Frames/train'

# Leer la lista de archivos desde el .list
with open(list_file, 'r') as f:
    file_list = f.read().splitlines()

# Archivos esperados para el set de entrenamiento
expected_files = set()

# Procesar cada línea en la lista
for file_path in file_list:
    # Nos interesa solo los archivos que empiezan con "train"
    if file_path.startswith('train/'):
        # Extraer el nombre del archivo sin ruta y sin extensión .npy
        file_name = os.path.basename(file_path).replace('.npy', '')
        if file_name in expected_files:
            continue
        else:
            expected_files.add(file_name)
    
# Verificar archivos faltantes


missing_files = []

# Recorrer las carpetas dentro de "train"
for root, dirs, files in os.walk(train_folder):
    for file in files:
        # Remover la extensión del archivo para compararlo
        file_name = os.path.splitext(file)[0]
        if file_name not in expected_files:
            print(f'Archivo faltante: {file_name}')
            missing_files.append(file_name)

# Resumen de archivos faltantes
if missing_files:
    print(f'Se encontraron {len(missing_files)} archivos faltantes en la carpeta train.')
else:
    print('Todos los archivos de la lista están presentes en la carpeta train.')
